name: 3dgs-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=12.2
  - plyfile
  - python=3.9.21
  - pip=24.2
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib